colorScheme = "autumn"
disableImageOptimization = true
defaultBackgroundImage = "OurLadyofLebanonExt.jpg"
favicon = "favicon.ico"
mainSections = [ "bulletins", "events" ]
enableSearch = false

[article]
  showPagination = false

[header]
  layout = "basic"

[list]
  showHero = true
  heroStyle = "background"

[homepage]
  #layout = "hero" "profile" "page" "hero" "card"
  #layout = "card"
  layout = "background"
  #layout = "card"
  cardView = false
  #heroStyle = "big" "basic" "background" "thumbAndBackground"
  heroStyle = "background"
  showRecent = true
  layoutBackgroundBlur = false
  disableHeroImageFilter = true
  #homepageImage = "OurLadyofLebanonExt.jpg"
  #homepageImage = "Choirwindow.jpg"
  #homepageImage = "NormandieMedallions.jpg"
  #homepageImage = "mural2.jpg"
  homepageImage = "OurLadyLebanonHenryStDoors.jpg"

[footer]
  showCopyright = false
  showThemeAttribution = false
