name: Build and deploy

on:
  push:
    branches:
      - master

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: '0.154.4'
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install Hugo
        env:
          HUGO_TAR: hugo_extended_${{ env.HUGO_VERSION }}_linux-amd64.tar.gz
        run: |
          curl -sLJO "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/${HUGO_TAR}"
          mkdir -p "${HOME}/.local/hugo"
          tar -C "${HOME}/.local/hugo" -xf "${HUGO_TAR}"
          rm "${HUGO_TAR}"

          echo "${HOME}/.local/hugo" >> "${GITHUB_PATH}"

      - name: Install lftp and poppler
        run: |
          sudo apt-get install -y lftp poppler-utils

      - name: Verify installations
        run: |
          echo 'Hugo:'
          hugo version   | cat -n
          echo '-----'
          echo 'lftp:'
          lftp --version | cat -n
          echo '-----'

      - name: Build the site
        run: |
          hugo build

          cp content/bulletins/*.pdf public/bulletins

      - name: Check PDF
        run: |
          ls -l static/bulletins content/bulletins public/bulletins

          cd public/bulletins
          md5sum --check <(
            cd ../../content/bulletins
            md5sum *.pdf
          )

      - name: Publish to ololc.org
        env:
          FTP_HOST: ${{vars.FTP_HOST}}
          FTP_USER: ${{vars.FTP_USER}}
          FTP_PASS: ${{secrets.FTP_PASS}}
        run: |
          cd public
          lftp <<-EOF
          	set ssl:check-hostname no
          	open ${FTP_HOST} -u ${FTP_USER},${FTP_PASS}
          	cd www/new
          	mirror -R
          	exit
          EOF

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: ololc-org-site
          path: ./public

